#!/usr/bin/env python

import scraperwiki
import requests
import lxml.html


html = requests.get("http://abilitazione.miur.it/public/pubblicarisultati.php").content

# retrieve list of sectors from home page

dom = lxml.html.fromstring(html)
for sec in dom.cssselect("#frmCercaId select option"):
        sector = {'code': sec.get('value'), 'name': sec.text_content()}
        if sector['code'] is not in ['1', '2']:
            scraperwiki.sql.save(['code', 'name'], sector, table_name="sectors")

# for each list, retrieve single items (id, name, indicators URL, CV PDF, assessment PDF, yes/no)



# Saving data:
# unique_keys = [ 'id' ]
# data = { 'id':12, 'name':'violet', 'age':7 }
# scraperwiki.sql.save(unique_keys, data)
