#!/usr/bin/env python

import scraperwiki
import requests
import lxml.html


html = requests.get("http://abilitazione.miur.it/public/pubblicarisultati.php").content

dom = lxml.html.fromstring(html)
for sec in dom.cssselect("#frmCercaId select option"):
    print(sec.value)

# retrieve list of sectors



# for each list, retrieve single items (id, name, indicators URL, CV PDF, assessment PDF, yes/no)



# Saving data:
# unique_keys = [ 'id' ]
# data = { 'id':12, 'name':'violet', 'age':7 }
# scraperwiki.sql.save(unique_keys, data)
